version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=people
    ports:
      - "5432:5432"

  cadastrarpessoa:
    image: primeiraimage:latest
    environment:
      - spring.datasource.url=jdbc:postgresql://postgres:5432/people
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  pessoacadastrar:
    image: segundaimage:latest
    environment:
      - spring.datasource.url=jdbc:postgresql://postgres:5432/people
    ports:
      - "8080:8080"
    depends_on:
      - postgres