version: '3'
name: cadastrarpessoa
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=people
    ports:
      - "5432:5432"

  jaeger:
    image: jaegertracing/all-in-one
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 14250:14250
      - 9411:9411
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411

  contas:
    image: 'zupacademy/contas'
    ports:
      - 8888:8888
    environment:
      SERVER_PORT: 8888
      LOG_LEVEL: INFO
      JAEGER_ENDPOINT: http://jaeger:14268/api/traces

  analise:
    image: 'zupacademy/analise-financeira'
    ports:
      - 9999:9999
    environment:
      SERVER_PORT: 9999
      LOG_LEVEL: INFO
      URL_SISTEMA_CARTAO: http://contas:8888/api/cartoes
      JAEGER_ENDPOINT: http://jaeger:14268/api/traces