version: '3'
name: cadastrarpessoa
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=people
    ports:
      - "5432:5432"

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000
    extra_hosts:
      - "moby:127.0.0.1"

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:32181"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:29092"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "29092:29092"


#version: '3'
#name: cadastrarpessoa
#services:
#  postgres:
#    image: postgres:latest
#    container_name: postgres
#    restart: always
#    environment:
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
#      - POSTGRES_DB=people
#    ports:
#      - 5432:5432
#  #      - 5433:5432
#
#  zookeeper:
#    image: confluentinc/cp-zookeeper:latest
#    environment:
#      ZOOKEEPER_CLIENT_PORT: 32181
#      ZOOKEEPER_TICK_TIME: 2000
#    extra_hosts:
#      - "moby:127.0.0.1"
#
#  kafka:
#    image: confluentinc/cp-kafka:latest
#    depends_on:
#      - zookeeper
#    environment:
#      KAFKA_BROKER_ID: 1
#      KAFKA_ZOOKEEPER_CONNECT: localhost:32181
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:29092
#      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#    volumes:
#      - custom-hosts:/path/to/mount
#
#volumes:
#  custom-hosts:
#    driver: local
#    driver_opts:
#      type: none
#      device: ./custom-hosts
#      o: bind
#
#
#
#  #  volumes:
##    custom-hosts:
##      driver: local
##      driver_opts:
##        type: none
##        device: ./custom-hosts
##        o: bind
#
#
#  #  jaeger:
#  #    image: jaegertracing/all-in-one
#  #    ports:
#  #      - 5775:5775/udp
#  #      - 6831:6831/udp
#  #      - 6832:6832/udp
#  #      - 5778:5778
#  #      - 16686:16686
#  #      - 14268:14268
#  #      - 14250:14250
#  #      - 9411:9411
#  #    environment:
#  #      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
#  #
#  #  contas:
#  #    image: 'zupacademy/contas'
#  #    ports:
#  #      - 8888:8888
#  #    environment:
#  #      SERVER_PORT: 8888
#  #      LOG_LEVEL: INFO
#  #      JAEGER_ENDPOINT: http://jaeger:14268/api/traces
#  #
#  #  analise:
#  #    image: 'zupacademy/analise-financeira'
#  #    ports:
#  #      - 9999:9999
#  #    #      - 9998:9999
#  #    environment:
#  #      SERVER_PORT: 9999
#  #      LOG_LEVEL: INFO
#  #      URL_SISTEMA_CARTAO: http://contas:8888/api/cartoes
#  #      JAEGER_ENDPOINT: http://jaeger:14268/api/traces
#
